from django.conf.urls import url, patterns, include
from rest_framework import routers
from . import views

# URIs generated by ngResource don't use a trailing slash, so we disable the
# manditory trailing slash here (to avoid redirects and all other sorts of bs).
# I also feel like api/foobar/<pk> reads better than api/foobar/<pk>/ but
# maybe that's just me.
router = routers.DefaultRouter(trailing_slash=False)
router.register(r'articles', views.ArticleViewSet)
router.register(r'categories', views.CategoryViewSet)

urlpatterns = patterns(
    '',
    url(r'^api/', include(router.urls)),
    )